<a href="https://colab.research.google.com/github/varshasisodiya16-arch/first-repository/blob/main/diabetes_data_analyses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/diabetes.csv")

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.head(4)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0

In [ ]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.shape

(768, 9)

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
# to check missing value
df.isnull().count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [ ]:
#check the duplicate values
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [ ]:
df.duplicated().count()

np.int64(768)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [ ]:
# check the invalid zero values
(df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]==0).sum()

Glucose            5
BloodPressure     35
SkinThickness    227
Insulin          374
BMI               11
dtype: int64

selsecting the data and filter the *date*

In [ ]:
#select a column
df['BloodPressure']

0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64

In [ ]:
df[['Age','BloodPressure']]
#multiple column

     Age  BloodPressure
0     50             72
1     31             66
2     32             64
3     21             66
4     33             40
..   ...            ...
763   63             76
764   27             70
765   30             72
766   47             60
767   23             70

[768 rows x 2 columns]

In [ ]:
#filter rows by some conditions
df[df['Age']>60].count()

Pregnancies                 27
Glucose                     27
BloodPressure               27
SkinThickness               27
Insulin                     27
BMI                         27
DiabetesPedigreeFunction    27
Age                         27
Outcome                     27
dtype: int64

In [ ]:
#filter with multiple condition
df[(df['Age'] > 65) & (df['Outcome'] == 1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
221,2,158,90,0,0,31.6,0.805,66,1
363,4,146,78,0,0,38.5,0.520,67,1
666,4,145,82,18,0,32.5,0.235,70,1
759,6,190,92,0,0,35.5,0.278,66,1

In [ ]:
#access rows by index
df.iloc[700:709]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
700,2,122,76,27,200,35.9,0.483,26,0
701,6,125,78,31,0,27.6,0.565,49,1
702,1,168,88,29,0,35.0,0.905,52,1
703,2,129,0,0,0,38.5,0.304,41,0
704,4,110,76,20,100,28.4,0.118,27,0
705,6,80,80,36,0,39.8,0.177,28,0
706,10,115,0,0,0,0.0,0.261,30,1
707,2,127,46,21,335,34.4,0.176,22,0
708,9,164,78,0,0,32.8,0.148,45,1

Sorting and grouping

In [ ]:
#sort by using a column
df.sort_values(by='Age')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
736,0,126,86,27,120,27.4,0.515,21,0
738,2,99,60,17,160,36.6,0.453,21,0
721,1,114,66,36,200,38.1,0.289,21,0
60,2,84,0,0,0,0.0,0.304,21,0
290,0,78,88,29,40,36.9,0.434,21,0
...,...,...,...,...,...,...,...,...,...
123,5,132,80,0,0,26.8,0.186,69,0
684,5,136,82,0,0,0.0,0.640,69,0
666,4,145,82,18,0,32.5,0.235,70,1
453,2,119,0,0,0,19.6,0.832,72,0
459,9,134,74,33,60,25.9,0.460,81,0

In [ ]:
#Value count
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
# Statistics
# mean of column
df['BMI'].mean()

np.float64(31.992578124999998)

In [ ]:
#Median
df['Glucose'].median()

117.0

Modification of data

In [ ]:
# add a ner=w column
df['BloodPressure_CATEGORY']=pd.cut(df['BloodPressure'],bins[5, 5],labels=[h,S])

NameError: name 'bins' is not defined

In [ ]:
# replace invalid zeroes
df['Insulin']= df['Insulin'].replace(0,df['Insulin'].mean)

Data visualisation

# Hitogram
import matplotlib.pyplot as plt
import seaborn as sns
plt.hist(df[Age])
plt.xlabel('Age')
plt.ylabel('Frequency)

In [ ]:
#Histogram
import matplotlib.pyplot as plt
import seaborn as sns

plt.hist(df['Age'])
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution')
plt.show()

NameError: name 'df' is not defined